stages:
    - test

test_job:
    image: golang:alpine
    stage: test
    script:
        - apk add --update git
        - mkdir -p /go/src/gitlab.com
        - ln -s /builds/HokieGeek /go/src/gitlab.com/hokiegeek
        - cd /go/src/gitlab.com/hokiegeek/life
        - go get -d -v .
        - go test -covermode=count -v .
