stages:
    - test
      #    - build_image

test_job:
    image: golang:alpine
    stage: test
    script:
        - apk add --update git
        - mkdir -p /go/src/gitlab.com
        - ln -s /builds/HokieGeek /go/src/gitlab.com/hokiegeek
        - cd /go/src/gitlab.com/hokiegeek/life
        - go get -d -v .
        - go test -covermode=count -v .

build_image_job:
    image: docker:git
    stage: build_image
    services:
        - docker:dind
    script:
        - export IMAGE_NAME=registry.gitlab.com/hokiegeek/life:$CI_BUILD_REF_NAME
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
