#!/bin/sh

[ $# -gt 0 -a "$1" == "--kill" ] && {
    pkill lifed
    pkill -f SimpleHTTPServer
    exit 0
}

echo "[Starting lifed server]"

me=$(cd $(dirname $0); pwd)
cd ${me}

pkill lifed

# [ $# -gt 0 ] && lifedPort=$1 || lifedPort=8080

rm -rf lifed
go build lifed.go && ./lifed --port 8081 | tee lifed.log &

cd ~/src/web/life-web
./run &
